# Generated by Django 3.2.25 on 2026-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
