# Generated by Django 3.2.25 on 2026-02-13 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('main_dish', models.CharField(help_text='Main dish (e.g., Dal, Sabzi)', max_length=100)),
                ('side_dish', models.CharField(blank=True, help_text='Side dish (e.g., Roti, Rice)', max_length=100)),
                ('additional_items', models.TextField(blank=True, help_text='Additional items (e.g., Salad, Pickle)')),
                ('extra_portions', models.PositiveIntegerField(default=1, help_text='Extra portions available (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_per_portion', models.DecimalField(decimal_places=2, help_text='Fixed price per extra portion', max_digits=6)),
                ('order_cutoff_time', models.TimeField(help_text='Last time to order this meal')),
                ('max_orders', models.PositiveIntegerField(default=5)),
                ('current_orders', models.PositiveIntegerField(default=0)),
                ('pickup_available', models.BooleanField(default=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_radius', models.PositiveIntegerField(default=3, help_text='Delivery radius in km')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('chef', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('cooking_experience', models.PositiveIntegerField(default=5, help_text='Years of cooking experience')),
                ('cuisine_specialties', models.CharField(help_text='e.g., North Indian, South Indian, Chinese', max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('kitchen_type', models.CharField(choices=[('home', 'Home Kitchen'), ('dedicated', 'Dedicated Kitchen Space')], default='home', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('chef', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback (max 200 chars)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reviews', to=settings.AUTH_USER_MODEL)),
                ('daily_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chefs.dailymeal')),
            ],
            options={
                'unique_together': {('daily_meal', 'customer')},
            },
        ),
    ]
