# Generated by Django 3.2.25 on 2026-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_chefprofile_customerreview_dailyearning_dailymeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location-based searches', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location-based searches', max_digits=9, null=True),
        ),
    ]
