# Generated by Django 3.2.25 on 2026-03-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_auto_20260302_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20),
        ),
    ]
