# Generated by Django 3.2.25 on 2026-03-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_alter_dailymeal_meal_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymeal',
            unique_together=set(),
        ),
    ]
