# Generated by Django 3.2.25 on 2026-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_remove_unique_constraint_dailymeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='order_cutoff_time',
            field=models.TimeField(default='20:00:00', help_text='Last time to order this meal'),
        ),
    ]
