# Generated by Django 3.2.25 on 2026-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0006_alter_dailymeal_order_cutoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from customers (1-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of orders delivered on time', max_digits=5),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='total_orders_completed',
            field=models.PositiveIntegerField(default=0, help_text='Total number of orders completed'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received'),
        ),
    ]
