# Generated by Django 3.2.25 on 2026-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating received (1-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef'), ('customer', 'Customer'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
