# Generated by Django 3.2.25 on 2026-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_identifier',
            field=models.CharField(blank=True, help_text="Custom address identifier like 'Near Central Park'", max_length=100, null=True),
        ),
    ]
