# Generated by Django 3.2.25 on 2026-08-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_dailymealorder_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_customeraddress_address_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars')),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback about the customer (max 300 chars)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_customer_ratings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ratings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ratings', to='orders.dailymealorder')),
            ],
            options={
                'unique_together': {('customer', 'order')},
            },
        ),
    ]
