# Generated by Django 3.2.25 on 2026-02-13 16:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs', '0002_chefprofile_customerreview_dailyearning_dailymeal'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('portions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_per_portion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Local Delivery')], default='pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True, help_text='Required for delivery orders')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions (max 200 chars)', max_length=200)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('chef_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to=settings.AUTH_USER_MODEL)),
                ('daily_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='chefs.dailymeal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars')),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback (max 200 chars)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('daily_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.dailymealorder')),
            ],
        ),
    ]
